# Package Overview
package_name: regression

# Data files
training_data: train.csv
test_data: test.csv

# Variables
# The variable we are attempting to predict (loan amount)
target: loanamount

pipeline_name: loan_pred_regression_model
pipeline_save_file: loan_pred_regression_model_output_v

features:
  - married
  - dependents
  - education
  - self_employed
  - applicantincome
  - coapplicantincome
  - loan_amount_term
  - credit_history
  - property_area

# set the train/test split size
test_size: 0.2

# to set the random seed
random_state: 1

# hyperparameters
learning_rate: 0.01

max_depth: 4

max_iter: 200

n_estimators: 200

tol: 0.0074

C: 1

cat_vars_na: 
  - married
  - dependents
  - self_employed

num_var_na: 
  - loan_amount_term

num_cont_vars:
  - applicantincome
  - coapplicantincome

cat_vars:
  - married
  - dependents
  - education
  - self_employed
  - credit_history
  - property_area

mapper:
  1.0: 'yes' 
  0.0: 'no'
  nan: 'no'


credit_var_mapper: 
  - credit_history