version: '3.7'

networks:
  frontend:
  backend:

services:
  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter-notebook
    user: root
    environment:
      GRANT_SUDO: "yes"
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/work
    networks:
      - backend
      - frontend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./db_data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend

  grafana:
    image: grafana/grafana
    user: "100"
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend
    restart: always
    volumes:
      - ./config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro

volumes:
  grafana_data: {}
  db_data: